var value = true;
var value1 = false;
let print = true;
let print1 = false;
const count = true;
const count1 = false;
console.log(typeof value);
console.log(typeof value1);
console.log(typeof print);
console.log(typeof print1);
console.log(typeof count);
console.log(typeof count1);
